package com.example.vladimir.worldtour;


import android.app.FragmentTransaction;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.Toast;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity implements DestinationsFragment.IDestinationsHandler, CountryDetailsFragment.ICountryHandler {

    DestinationsFragment destinationsFragment;
    CountryDetailsFragment countryDetailsFragment;
    CapitalDetailsFragment capitalDetailsFragment;
    ArrayList<Destination> destinations;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        destinationsFragment = new DestinationsFragment();
        countryDetailsFragment = new CountryDetailsFragment();
        capitalDetailsFragment = new CapitalDetailsFragment();

        getFragmentManager().beginTransaction().replace(R.id.placeholder,destinationsFragment).commit();

        generateCountriesAndCapitals();
    }

    @Override
    public void onDestinationClicked(Integer index) {
        if(destinations.size()>index){
            Destination dest = destinations.get(index);
            countryDetailsFragment.setCountry(dest,index);

            FragmentTransaction ft = getFragmentManager().beginTransaction();
            ft.replace(R.id.placeholder, countryDetailsFragment);
            ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_OPEN);
            ft.addToBackStack(null);// <-- MAGIC!
            ft.commit();
        }
        else{
            Toast.makeText(this,"This button doesn't work :(",Toast.LENGTH_SHORT).show();
        }


    }

    @Override
    public void onBackPressed() {
        setTitle("Choose destination");
        super.onBackPressed();
    }

    @Override
    public void onCapitalBtnClick(Integer index) {
        Capital capital = destinations.get(index).getCapital();
        capitalDetailsFragment.setCapital(capital);

        FragmentTransaction ft = getFragmentManager().beginTransaction();
        ft.replace(R.id.placeholder, capitalDetailsFragment);
        ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_OPEN);
        ft.addToBackStack(null);
        ft.commit();
    }

    private void generateCountriesAndCapitals() {
        destinations = new ArrayList<>();
        destinations.add(new Destination("Bulgaria","Bulgarian",new Capital("Sofia", R.drawable.sofia_image,"   Sofia is the capital and largest city of Bulgaria. The city has a population of 1.26 million, while over 1.5 million people live in its functional urban area. The city is located at the foot of Vitosha Mountain in the western part of the country, within less than 50 kilometres drive from the Serbian border. Its location in the centre of the Balkan peninsula means that it is the midway between the Black Sea and the Adriatic Sea, whereas the Aegean Sea is the closest to it.\n" +
                "   Sofia has been an area of human habitation since at least 7000 BC. Being Bulgaria's primate city, Sofia is a hometown of many of the major local universities, cultural institutions and commercial companies. Sofia is one of the top 10 best places for start-up business in the world, especially in IT technologies. Sofia is Europe's most affordable capital to visit as of 2013."),"   Bulgaria, officially the Republic of Bulgaria, is a country in southeastern Europe. It is bordered by Romania to the north, Serbia and Macedonia to the west, Greece and Turkey to the south, and the Black Sea to the east. With a territory of 110,994 square kilometres, Bulgaria is Europe's 16th-largest country.\n" +
                "   Organised prehistoric cultures began developing on current Bulgarian lands during the Neolithic period. Its ancient history saw the presence of the Thracians, Greeks and Romans. The emergence of a unified Bulgarian state dates back to the establishment of the First Bulgarian Empire in 681 AD, which dominated most of the Balkans and functioned as a cultural hub for Slavs during the Middle Ages. With the downfall of the Second Bulgarian Empire in 1396, its territories came under Ottoman rule for nearly five centuries. The Russo-Turkish War of 1877–78 led to the formation of the Third Bulgarian State. The following years saw several conflicts with its neighbours, which prompted Bulgaria to align with Germany in both world wars. In 1946 it became a one-party socialist state as part of the Soviet-led Eastern Bloc. In December 1989 the ruling Communist Party allowed multi-party elections, which subsequently led to Bulgaria's transition into a democracy and a market-based economy.\n" +
                "   Bulgaria's population of 7.4 million people is predominantly urbanised and mainly concentrated in the administrative centres of its 28 provinces. Most commercial and cultural activities are centred on the capital and largest city, Sofia. The strongest sectors of the economy are heavy industry, power engineering, and agriculture, all of which rely on local natural resources.",R.drawable.bulgaria_emblem));
        destinations.add(new Destination("Germany","German",new Capital("Berlin",R.drawable.berlin_image,"   Berlin is the capital and the largest city of Germany as well as one of its 16 states. With a population of approximately 3.6 million people, Berlin is the second most populous city proper and the seventh most populous urban area in the European Union. Located in northeastern Germany on the banks of Rivers Spree and Havel, it is the centre of the Berlin-Brandenburg Metropolitan Region, which has about 6 million residents from more than 180 nations. Due to its location in the European Plain, Berlin is influenced by a temperate seasonal climate. Around one-third of the city's area is composed of forests, parks, gardens, rivers and lakes.\n" +
                "   First documented in the 13th century and situated at the crossing of two important historic trade routes, Berlin became the capital of the Margraviate of Brandenburg (1417–1701), the Kingdom of Prussia (1701–1918), the German Empire (1871–1918), the Weimar Republic (1919–1933) and the Third Reich (1933–1945). Berlin in the 1920s was the third largest municipality in the world. After World War II, the city was divided; East Berlin became the capital of East Germany while West Berlin became a de facto West German exclave, surrounded by the Berlin Wall (1961–1989) and East Germany territory. Following German reunification in 1990, Berlin was once again designated as the capital of united Germany.\n" +
                "   Berlin is a world city of culture, politics, media and science. Its economy is based on high-tech firms and the service sector, encompassing a diverse range of creative industries, research facilities, media corporations and convention venues. Berlin serves as a continental hub for air and rail traffic and has a highly complex public transportation network. The metropolis is a popular tourist destination. Significant industries also include IT, pharmaceuticals, biomedical engineering, clean tech, biotechnology, construction and electronics.\n" +
                "   Modern Berlin is home to world renowned universities, orchestras, museums, entertainment venues and is host to many sporting events. Its urban setting has made it a sought-after location for international film productions. The city is well known for its festivals, diverse architecture, nightlife, contemporary arts and a high quality of living. Over the last decade Berlin has seen the emergence of a cosmopolitan entrepreneurial scene."),"   Germany, officially the Federal Republic of Germany, is a federal parliamentary republic in central-western Europe. It includes 16 constituent states, covers an area of 357,021 square kilometres, and has a largely temperate seasonal climate. Its capital and largest city is Berlin. With about 82.0 million inhabitants, Germany is the most populous member state of the European Union. After the United States, it is the second most popular human migration destination.\n" +
                "   Various Germanic tribes have occupied the northern parts of modern Germany since classical antiquity. A region named Germania was documented before 100 AD. During the Migration Period the Germanic tribes expanded southward. Beginning in the 10th century, German territories formed a central part of the Holy Roman Empire. During the 16th century, northern German regions became the centre of the Protestant Reformation.\n" +
                "   In 1871 most of the German states unified into the Prussian-dominated German Empire. After World War I and the German Revolution of 1918–1919, the Empire was replaced by the parliamentary Weimar Republic. The establishment of the national socialist dictatorship in 1933 led to World War II and systematic genocide. After a period of Allied occupation, two German states were founded: the Federal Republic of Germany and the German Democratic Republic. In 1990, the country was reunified.\n" +
                "   In the 21st century, Germany is a great power and has the world's fourth-largest economy by nominal GDP, as well as the fifth-largest by PPP. As a global leader in several industrial and technological sectors, it is both the world's third-largest exporter and importer of goods. Germany is a developed country with a very high standard of living sustained by a skilled and productive society. It upholds a social security and universal health care system, environmental protection and a tuition-free university education.\n" +
                "   Germany was a founding member of the European Union in 1993. It is part of the Schengen Area, and became a co-founder of the Eurozone in 1999. Germany is a member of the United Nations, NATO, the G8, the G20, and the OECD. The national military expenditure is the 9th highest in the world. Known for its rich cultural history, Germany has been continuously the home of influential artists, philosophers, musicians, sportspeople, entrepreneurs, scientists and inventors.",R.drawable.germany_emblem));
        destinations.add(new Destination("Italy","Italian",new Capital("Rome",R.drawable.rome_image,"   Rome (/ˈroʊm/ rohm; Italian: Roma [ˈroːma] ( listen), Latin: Rōma) is a city and special comune (named Roma Capitale) in Italy. Rome is the capital of Italy and of the Lazio region. With 2.9 million residents in 1,285 km2 (496.1 sq mi), it is also the country's largest and most populated comune and fourth-most populous city in the European Union by population within city limits. The Metropolitan City of Rome has a population of 4.3 million residents.[2] The city is located in the central-western portion of the Italian Peninsula, within Lazio (Latium), along the shores of Tiber river. The Vatican City is an independent country geographically located within the city boundaries of Rome, the only existing example of a country within a city: for this reason Rome has been often defined as capital of two states.[3][4]\n" +
                "   Rome's history spans more than two and a half thousand years. While Roman mythology dates the founding of Rome at only around 753 BC, the site has been inhabited for much longer, making it one of the oldest continuously occupied sites in Europe.[5] The city's early population originated from a mix of Latins, Etruscans and Sabines. Eventually, the city successively became the capital of the Roman Kingdom, the Roman Republic and the Roman Empire, and is regarded as one of the birthplaces of Western civilisation and by some as the first ever metropolis.[6] It is referred to as \"Roma Aeterna\" (The Eternal City)[7] and \"Caput Mundi\" (Capital of the World), two central notions in ancient Roman culture.\n" +
                "   After the fall of the Western Empire, which marked the beginning of the Middle Ages, Rome slowly fell under the political control of the Papacy, which had settled in the city since the 1st century AD, until in the 8th century it became the capital of the Papal States, which lasted until 1870.\n" +
                "   Beginning with the Renaissance, almost all the popes since Nicholas V (1422–55) pursued coherently along four hundred years an architectonic and urbanistic programme aimed to make of the city the world's artistic and cultural centre.[8] Due to that, Rome became first one of the major centres of the Italian Renaissance,[9] and then the birthplace of both the Baroque style and Neoclassicism. Famous artists, painters, sculptors and architects made Rome the centre of their activity, creating masterpieces throughout the city. In 1871 Rome became the capital of the Kingdom of Italy, and in 1946 that of the Italian Republic.\n" +
                "   Rome has the status of a global city.[10][11][12] Rome ranked in 2014 as the 14th-most-visited city in the world, 3rd most visited in the European Union, and the most popular tourist attraction in Italy.[13] Its historic centre is listed by UNESCO as a World Heritage Site.[14] Monuments and museums such as the Vatican Museums and the Colosseum are among the world's most visited tourist destinations with both locations receiving millions of tourists a year. Rome hosted the 1960 Summer Olympics and is the seat of United Nations' Food and Agriculture Organization (FAO)."),"   Italy (Italian: Italia [iˈtaːlja] ( listen)), officially the Italian Republic (Italian: Repubblica Italiana),[7][8][9][10] is a unitary parliamentary republic in Europe.[note 1] Located in the heart of the Mediterranean Sea, Italy shares open land borders with France, Switzerland, Austria, Slovenia, San Marino and Vatican City. Italy covers an area of 301,338 km2 (116,347 sq mi) and has a largely temperate seasonal climate or Mediterranean climate; due to its shape, it is often referred to in Italy as lo Stivale (the Boot).[11][12] With 61 million inhabitants, it is the third most populous EU member state.\n" +
                "   Since classical times, ancient Phoenicians and Greeks, Etruscans, and Celts have inhabited the south, centre and north of the Italian Peninsula respectively, with various Italic peoples dispersed throughout Italy alongside other ancient Italian tribes and Greek, Carthaginian, and Phoenician colonies. The Italic tribe known as the Latins formed the Roman Kingdom, which eventually spread throughout Italy, assimilating and conquering other nearby civilisations and forming the Roman Republic. Rome ultimately emerged as the dominant power, conquering much of the ancient world and becoming the leading cultural, political, and religious centre of Western civilisation. The legacy of the Roman Empire is widespread and can be observed in the global distribution of civilian law, republican governments, Christianity and the Latin script.\n" +
                "   During the Middle Ages, Italy suffered sociopolitical collapse amid calamitous barbarian invasions, but by the 11th century, numerous rival city-states and maritime republics rose to great prosperity through shipping, commerce, and banking, and even laid the groundwork for capitalism.[13] These independent city-states and regional republics, acting as Europe's main port of entry for Asian and Near Eastern imported goods, often enjoyed a greater degree of democracy in comparison to the monarchies and feudal states found throughout Europe at the time, though much of central Italy remained under the control of the theocratic Papal States, while Southern Italy remained largely feudal, partially as a result of a succession of Byzantine, Arab, Norman, Spanish, and Bourbon conquests of the region.[14]\n" +
                "   The Renaissance began in Italy and spread to the rest of Europe, bringing a renewed interest in humanism, science, exploration, and art with the start of the modern era. Italian culture flourished at this time, producing famous scholars, artists, and polymaths such as Leonardo da Vinci, Galileo, Michelangelo, and Machiavelli. Explorers from Italy such as Marco Polo, Christopher Columbus, Amerigo Vespucci, and Giovanni da Verrazzano discovered new routes to the Far East and the New World, helping to usher in the European Age of Discovery. Nevertheless, Italy's importance as a hub of commercial and political power significantly waned with the opening of trade routes from the New World, as New World imports and trade routes became more influential in Europe and bypassed the East Asian and Mediterranean trade routes that the Italian city-states had dominated.[14][15][16] Furthermore, the Italian city-states constantly engaged one another in bloody warfare, with this tension and violent rivalry culminating in the Italian Wars of the 15th and 16th centuries, a series of wars and foreign invasions that left the Italian states vulnerable to annexation by neighbouring European powers. Italy would remain politically fragmented and fall prey to conquest, occupation, and general foreign domination by European powers such as France, Spain, and Austria, subsequently entering a long period of decline.\n" +
                "   By the mid-19th century, a rising movement in support of Italian nationalism and Italian independence from foreign control lead to a period of revolutionary political upheaval known as the Risorgimento, which sought to bring about a rebirth of Italian cultural and economic prominence by liberating and consolidating the Italian peninsula and insular Italy into an independent and unified nation-state. After various unsuccessful attempts, the Italian Wars of Independence, the Expedition of the Thousand and the capture of Rome resulted in the eventual unification of the country, now a great power after centuries of foreign domination and political division.[17] From the late 19th century to the early 20th century, the new Kingdom of Italy rapidly industrialised, especially in the so-called Industrial Triangle of Milan, Turin and Genoa in the north, and soon acquired a small colonial empire.[18][19] However, the southern areas of the country remained largely impoverished and excluded from industrialisation, fuelling a large and influential diaspora. Despite being one of the main victors in World War I, Italy entered a period of economic crisis and social turmoil, leading the way to the rise of a Fascist dictatorship in 1922. The subsequent participation in World War II on the Axis side ended in military defeat, economic destruction, and a civil war following the rise of the Italian resistance movement. In the years that followed, Italy abolished the Italian monarchy, reinstated democracy, enjoyed a prolonged economic boom, and, despite periods of sociopolitical turmoil (e.g. Anni di piombo, Mani pulite, Second Mafia War and Maxi Trial), became one of the world's most developed nations.[5][20][21][22]\n" +
                "   Italy has the third largest economy in the Eurozone and eighth largest economy in the world. It has a very high level of human development and enjoys the highest life expectancy in the EU.[23] Italy plays a prominent role in regional and global economic, military, cultural and diplomatic affairs, and the country is both a regional power[24] and a great power.[25][26] Italy is a founding and leading member of the European Union and the member of numerous international institutions, including the UN, NATO, the OECD, the OSCE, the WTO, the G7/G8, G20, the Union for the Mediterranean, the Council of Europe, Uniting for Consensus, and many more. As a reflection of its vast cultural wealth, Italy is home to 51 World Heritage Sites, the most in the world, and is one of the most visited countries.",R.drawable.italy_emblem));
        destinations.add(new Destination("France","French",new Capital("Paris",R.drawable.paris_image,"   Paris (French: [paʁi] ( listen)) is the capital and the most populous city of France. It has an area of 105 km² (41 mi²) and a population in 2013 of 2,229,621 within the city limits.[4] Paris is both a commune and department, and forms the centre and headquarters of the Île-de-France, or Paris Region, which has an area of 12,012 square kilometers (4,638 square miles) and a population in 2014 of 12,005,077, comprising 18.2 percent of the population of France.[5]\n" +
                "   Paris was founded in the 3rd century BC by a Celtic people called the Parisii, who gave the city its name. By the 12th century, Paris was the largest city in the western world, a prosperous trading centre, and the home of the University of Paris, one of the oldest universities in history. By the 17th century it was one of Europe's major centres of finance, commerce, fashion, science, and the arts, and it retains that position still today.\n" +
                "   Among Paris' important museums and cultural institutions are the most visited art museum in the world, the Louvre, as well as the Musée d'Orsay, noted for its collection of French Impressionist art, and the Musée National d'Art Moderne in the Pompidou Centre, the largest collection of modern and contemporary art in Europe. The Central area of Paris along the Seine River is classified as a UNESCO Heritage Site, and includes many notable monuments, including Notre Dame Cathedral (12th century); the Sainte-Chapelle (13th century); the Eiffel Tower (1889); the Grand and Petit Palais (1900); and the Basilica of Sacré-Cœur on Montmartre (1914). In 2015 Paris received 22.2 million visitors, making it one of the world's top tourist destinations.[6] and is also known for its fashion, particularly the twice-yearly Paris Fashion Week, and for its haute cuisine, and three-star restaurants. Most of France's major universities and grandes écoles are located in Paris, as are France's major newspapers, including Le Monde, Le Figaro, and Libération.\n" +
                "   The association football club Paris Saint-Germain and the rugby union club Stade Français are based in Paris. The 80,000-seat Stade de France, built for the 1998 FIFA World Cup, is located just north of Paris in the commune of Saint-Denis. Paris hosts the annual French Open Grand Slam tennis tournament on the red clay of Roland Garros. Paris hosted the 1900 and 1924 Summer Olympics, the 1938 and 1998 FIFA World Cups, the 2007 Rugby World Cup and UEFA Euro 2016. Every July, the Tour de France of cycling finishes in the city.\n" +
                "   The city is also a major rail, highway, and air-transport hub, served by the two international airports Paris-Charles de Gaulle (the second busiest airport in Europe after London Heathrow Airport with 63,8 millions passengers in 2014) and Paris-Orly. Opened in 1900, the city's subway system, the Paris Métro, serves 4.5 million passengers daily.[7] It is the second busiest metro system in Europe after Moscow Metro. Paris is the hub of the national road network, and is surrounded by three orbital roads: the Périphérique, the A86 motorway, and the Francilienne motorway.\n" +
                "   The agglomeration has grown well beyond Paris' administrative limits. The Paris unité urbaine is a measure of Paris' continuous urban area for statistical purposes, including both the commune and its suburbs, and has a population of 10,550,350 (Jan. 2012 census) which makes it the largest in the European Union.[2] The aire urbaine de Paris, a measure of Paris' metropolitan area, spans most of the Île-de-France region and has a population of 12,405,426 (Jan. 2013 census),[8] constituting one-fifth of the population of France.[9] The Metropole of Grand Paris was created in 2016, combining the city and its nearest suburbs into a single area for economic and environmental cooperation. Grand Paris covers 814 square kilometers and has a population of 6.945 million persons.[10]"),"   France (French: [fʁɑ̃s]), officially the French Republic (French: République française [ʁepyblik fʁɑ̃sɛz]), is a sovereign transcontinental state comprising territory in western Europe and several overseas regions and territories.[XVI] The European, or metropolitan, area of France extends from the Mediterranean Sea to the English Channel and the North Sea, and from the Rhine to the Atlantic Ocean. Overseas France include French Guiana on the South American continent and several island territories in the Atlantic, Pacific and Indian oceans. France spans 643,801 square kilometres (248,573 sq mi)[1] and has a total population of 66.7 million.[VI][8] It is a unitary semi-presidential republic with the capital in Paris, the country's largest city and main cultural and commercial centre. During the Iron Age, what is now metropolitan France was inhabited by the Gauls, a Celtic people. The area was annexed in 51 BC by Rome, which held Gaul until 486, when the Germanic Franks conquered the region and formed the Kingdom of France.\n" +
                "   France emerged as a major European power in the Late Middle Ages, with its victory in the Hundred Years' War (1337 to 1453) strengthening state-building and political centralisation. During the Renaissance, French culture flourished and a global colonial empire was established, which by the 20th century would be the second largest in the world.[9] The 16th century was dominated by religious civil wars between Catholics and Protestants (Huguenots). France became Europe's dominant cultural, political, and military power under Louis XIV.[10] In the late 18th century, the French Revolution overthrew the absolute monarchy, established one of modern history's earliest republics, and saw the drafting of the Declaration of the Rights of Man and of the Citizen, which expresses the nation's ideals to this day.\n" +
                "   In the 19th century Napoleon took power and established the First French Empire, whose subsequent Napoleonic Wars shaped the course of continental Europe. Following the collapse of the Empire, France endured a tumultuous succession of governments culminating with the establishment of the French Third Republic in 1870. France was a major participant in the First World War, from which it emerged victorious, and was one of the Allied Powers in the Second World War, but came under occupation by the Axis Powers in 1940. Following liberation in 1944, a Fourth Republic was established and later dissolved in the course of the Algerian War. The Fifth Republic, led by Charles de Gaulle, was formed in 1958 and remains to this day. Algeria and the colonies in Indochina became independent in the 1950s after long, bloody wars. Nearly all the other colonies became independent in the 1960s with minimal controversy and typically retained close economic and military connections with France.\n" +
                "   France has long been a global centre of art, science, and philosophy. It hosts Europe's third-largest number of cultural UNESCO World Heritage Sites (after Italy and Spain) and receives around 83 million foreign tourists annually, the most of any country in the world.[11] France is a developed country with the world's sixth-largest economy by nominal GDP[12] and ninth-largest by purchasing power parity.[13] In terms of aggregate household wealth, it ranks fourth in the world.[14] France performs well in international rankings of education, health care, life expectancy, and human development.[15][16] France remains a great power in the world,[17] being a founding member of the United Nations, where it serves as one of the five permanent members of the UN Security Council, and a founding and leading member state of the European Union (EU).[18] It is also a member of the Group of 7, North Atlantic Treaty Organization (NATO), Organisation for Economic Co-operation and Development (OECD), the World Trade Organization (WTO), and La Francophonie.",R.drawable.france_emblem));
        destinations.add(new Destination("China","Chinese",new Capital("Beijing",R.drawable.beijing_image,"   Beijing (Chinese: 北京; pinyin: běijīng), formerly romanized as Peking,[8] is the capital of the People's Republic of China and the world's third most populous city proper. It is also the world's most populous capital city. The city, located in northern China, is governed as a direct-controlled municipality under the national government with 16 urban, suburban, and rural districts.[9] Beijing Municipality is surrounded by Hebei Province with the exception of neighboring Tianjin Municipality to the southeast; together the three divisions form the Jingjinji metropolitan region and the national capital region of China.[10]\n" +
                "   Beijing is the second largest Chinese city by urban population after Shanghai and is the nation's political, cultural, and educational center.[11] It is home to the headquarters of most of China's largest state-owned companies, and is a major hub for the national highway, expressway, railway, and high-speed rail networks. The Beijing Capital International Airport is the second busiest in the world by passenger traffic.[12]\n" +
                "   The city's history dates back three millennia. As the last of the Four Great Ancient Capitals of China, Beijing has been the political center of the country for much of the past eight centuries.[13] The city is renowned for its opulent palaces, temples, parks, gardens, tombs, walls and gates,[14] and its art treasures and universities have made it a center of culture and art in China.[14] Encyclopædia Britannica notes that \"few cities in the world have served for so long as the political headquarters and cultural centre of an area as immense as China.\"[15] Beijing has seven UNESCO World Heritage Sites – the Forbidden City, Temple of Heaven, Summer Palace, Ming Tombs, Zhoukoudian, as well as parts of the Great Wall and the Grand Canal.[16] Beijing hosted the 2008 Summer Olympics and was chosen to host the 2022 Winter Olympics, which will make it the first city to ever host both events.[17]"),"   China, officially the People's Republic of China (PRC), is a sovereign state in East Asia. With a population of over 1.381 billion, it is the world's most populous state.[16] The state is governed by the Communist Party of China based in the capital of Beijing.[17] It exercises jurisdiction over 22 provinces, five autonomous regions, four direct-controlled municipalities (Beijing, Tianjin, Shanghai, and Chongqing), two mostly self-governing special administrative regions (Hong Kong and Macau), and claims sovereignty over Taiwan. China is a great power and a major regional power within Asia, and has been characterized as a potential superpower.[18][19]\n" +
                "   Covering approximately 9.6 million square kilometers, China is the world's second largest state by land area,[20] and either the third or fourth-largest by total area, depending on the method of measurement.[i] China's landscape is vast and diverse, ranging from forest steppes and the Gobi and Taklamakan Deserts in the arid north to subtropical forests in the wetter south. The Himalaya, Karakoram, Pamir and Tian Shan mountain ranges separate China from much of South and Central Asia. The Yangtze and Yellow Rivers, the third and sixth longest in the world, respectively, run from the Tibetan Plateau to the densely populated eastern seaboard. China's coastline along the Pacific Ocean is 14,500 kilometers (9,000 mi) long, and is bounded by the Bohai, Yellow, East China, and South China seas.\n" +
                "   China is one of the cradles of civilization, with its known history beginning with an ancient civilization – one of the world's earliest – that flourished in the fertile basin of the Yellow River in the North China Plain. For millennia, China's political system was based on hereditary monarchies known as dynasties. Since 221 bc, when the Qin Dynasty first conquered several states to form a Chinese empire, the state has expanded, fractured and reformed numerous times. The Republic of China (ROC) replaced the last dynasty in 1912, and ruled the Chinese mainland until 1949, when it was defeated by the Communist Party of China in the Chinese Civil War. The Communist Party established the People's Republic of China in Beijing on 1 October 1949, while the ROC government relocated to Taiwan with its present capital in Taipei. Both the ROC and PRC continue to claim to be the legitimate government of all China.\n" +
                "   China had the largest economy in the world for most of the past two thousand years, during which it has seen cycles of prosperity and decline.[21][22] Since the introduction of economic reforms in 1978, China has become one of the world's fastest-growing major economies. As of 2014, it is the world's second-largest economy by nominal GDP and largest by purchasing power parity (PPP). China is also the world's largest exporter and second-largest importer of goods.[23] China is a recognized nuclear weapons state and has the world's largest standing army and second-largest defense budget.[24][25] The PRC is a member of the United Nations, as it replaced the ROC as a permanent member of the U.N. Security Council in 1971. China is also a member of numerous formal and informal multilateral organizations, including the WTO, APEC, BRICS, the Shanghai Cooperation Organization (SCO), the BCIM and the G-20.",R.drawable.china_emblem));
        destinations.add(new Destination("Spain","Spanish",new Capital("Madrid",R.drawable.madrid_image,"   Madrid (/məˈdrɪd/, Spanish: [maˈðɾið], locally: [maˈðɾiθ, -ˈðɾi]) is the capital of Spain, and the largest municipality of the Community of Madrid. The population of the city is almost 3.2 million[4] with a metropolitan area population of approximately 6.5 million. It is the third-largest city in the European Union, after London and Berlin, and its metropolitan area is the third-largest in the European Union after London and Paris.[5][6][7][8] Located in south-western Europe, the city spans a total of 604.3 km2 (233.3 sq mi).[9]\n" +
                "   The city is located on the Manzanares in the centre of both the country and the Community of Madrid (which comprises the city of Madrid, its conurbation and extended suburbs and villages); this community is bordered by the autonomous communities of Castile and León and Castile-La Mancha. As the capital city of Spain, seat of government, and residence of the Spanish monarch, Madrid is also the political, economic and cultural centre of Spain.[10] The current mayor is Manuela Carmena from Ahora Madrid.\n" +
                "   The Madrid urban agglomeration has the third-largest GDP[11] in the European Union and its influences in politics, education, entertainment, environment, media, fashion, science, culture, and the arts all contribute to its status as one of the world's major global cities.[12][13] Madrid is home to two world-famous football clubs, Real Madrid and Atlético de Madrid. Due to its economic output, high standard of living, and market size, Madrid is considered the major financial centre of Southern Europe[14][15] and the Iberian Peninsula; it hosts the head offices of the vast majority of major Spanish companies, such as Telefónica, Iberia, and Repsol. Madrid is the 17th most livable city in the world according to Monocle magazine, in its 2014 index.[16][17]\n" +
                "   Madrid houses the headquarters of the World Tourism Organization (UNWTO), belonging to the United Nations Organization (UN), the SEGIB, the Organization of Ibero-American States (OEI), and the Public Interest Oversight Board (PIOB). It also hosts major international regulators of Spanish: the Standing Committee of the Association of Spanish Language Academies, headquarters of the Royal Spanish Academy (RAE), the Cervantes Institute and the Foundation of Urgent Spanish (Fundéu BBVA). Madrid organizes fairs such as FITUR,[18] ARCO,[19] SIMO TCI[20] and the Cibeles Madrid Fashion Week.[21]\n" +
                "   While Madrid possesses modern infrastructure, it has preserved the look and feel of many of its historic neighbourhoods and streets. Its landmarks include the Royal Palace of Madrid; the Royal Theatre with its restored 1850 Opera House; the Buen Retiro Park, founded in 1631; the 19th-century National Library building (founded in 1712) containing some of Spain's historical archives; a large number of national museums,[22] and the Golden Triangle of Art, located along the Paseo del Prado and comprising three art museums: Prado Museum, the Reina Sofía Museum, a museum of modern art, and the Thyssen-Bornemisza Museum, which completes the shortcomings of the other two museums.[23] Cibeles Palace and Fountain have become the monument symbol of the city.[dubious – discuss][unreliable source?][24][25] The Plaza was built in 1900 it was originally named Plaza de Castelar however this name was replaced, by the well known name it has become today, Plaza de Cibeles.[26]"),"   Spain (Listeni/ˈspeɪn/; Spanish: España [esˈpaɲa] ( listen)), officially the Kingdom of Spain (Spanish: Reino de España),[a][b] is a sovereign state largely located on the Iberian Peninsula in southwestern Europe, with archipelagos in the Atlantic Ocean and Mediterranean Sea, and several small territories on and near the North African coast. Its Mainland is bordered to the south and east by the Mediterranean Sea except for a small land boundary with Gibraltar; to the north and northeast by France, Andorra, and the Bay of Biscay; and to the west and northwest by Portugal and the Atlantic Ocean. Along with France and Morocco, it is one of only three countries to have both Atlantic and Mediterranean coastlines. Extending to 1,214 km (754 mi), the Portugal–Spain border is the longest uninterrupted border within the European Union.\n" +
                "   Spanish territory includes two archipelagos: the Balearic Islands, in the Mediterranean Sea, and the Canary Islands, in the Atlantic Ocean off the African coast. It also includes two major exclaves, Ceuta and Melilla, in continental North Africa; and the islands and peñones (rocks) of Alborán, Alhucemas, Chafarinas and Vélez de la Gomera. With an area of 505,990 km2 (195,360 sq mi), Spain is the largest country in Southern Europe, the second largest country in Western Europe and the European Union, and the fourth largest country in the European continent. By population, Spain is the sixth largest in Europe and the fifth in the European Union.\n" +
                "   Modern humans first arrived in the Iberian Peninsula around 35,000 years ago. Iberian cultures along with ancient Phoenician, Greek and Carthaginian settlements developed on the peninsula until it came under Roman rule around 200 BCE, after which the region was named Hispania. In the Middle Ages, the area was conquered by Germanic tribes and later by the Moors. Spain emerged as a unified country in the 15th century, following the marriage of the Catholic Monarchs and the completion of the centuries-long reconquest, or Reconquista, of the peninsula from the Moors in 1492. In the early modern period, Spain became one of history's first global colonial empires, leaving a vast cultural and linguistic legacy that includes over 500 million Spanish speakers, making Spanish the world's second most spoken first language, after Chinese and before English.\n" +
                "   Spain is a democracy organised in the form of a parliamentary government under a constitutional monarchy. It is a middle power and a developed country with the world's fourteenth largest economy by nominal GDP and sixteenth largest by purchasing power parity. It is a member of the United Nations (UN), the European Union (EU), the Council of Europe (CoE), the Organization of Ibero-American States (OEI), the North Atlantic Treaty Organization (NATO), the Organisation for Economic Co-operation and Development (OECD), the World Trade Organization (WTO) and many other international organisations.",R.drawable.spain_emblem));
        destinations.add(new Destination("Greece","Greek",new Capital("Athens",R.drawable.athens_image,"   Athens (/ˈæθᵻnz/;[2] Modern Greek: Αθήνα, Athína Greek pronunciation: [aˈθina], Ancient Greek: Ἀθῆναι Athēnai) is the capital and largest city of Greece. Athens dominates the Attica region and is one of the world's oldest cities, with its recorded history spanning over 3,400 years, and its earliest human presence starting somewhere between the 11th and 7th millennia BC.[3] Classical Athens was a powerful city-state that emerged in conjunction with the seagoing development of the port of Piraeus. A centre for the arts, learning and philosophy, home of Plato's Academy and Aristotle's Lyceum,[4][5] it is widely referred to as the cradle of Western civilization and the birthplace of democracy,[6][7] largely because of its cultural and political impact on the European continent, and in particular the Romans.[8] In modern times, Athens is a large cosmopolitan metropolis and central to economic, financial, industrial, maritime, political and cultural life in Greece. In 2015, Athens was ranked the world's 29th richest city by purchasing power[9] and the 67th most expensive[10] in a UBS study.\n" +
                "   Athens is recognised as a global city because of its location and its importance in shipping, finance, commerce, media, entertainment, arts, international trade, culture, education and tourism. It is one of the biggest economic centres in southeastern Europe, with a large financial sector, and its port Piraeus is both the largest passenger port in Europe,[11][12][13][14] and the second largest in the world.[15] The municipality (City) of Athens had a population of 664,046 (in 2011,[1] 796,442 in 2004)[16] within its administrative limits, and a land area of 39 km2 (15 sq mi).[17] The urban area of Athens (Greater Athens and Greater Piraeus) extends beyond its administrative municipal city limits, with a population of 3,090,508 (in 2011)[18] over an area of 412 km2 (159 sq mi).[17] According to Eurostat in 2004, the Athens Larger Urban Zone (LUZ) was the 7th most populous LUZ in the European Union (the 5th most populous capital city of the EU), with a population of 4,013,368. Athens is also the southernmost capital on the European mainland.\n" +
                "   The heritage of the classical era is still evident in the city, represented by ancient monuments and works of art, the most famous of all being the Parthenon, considered a key landmark of early Western civilization. The city also retains Roman and Byzantine monuments, as well as a smaller number of Ottoman monuments.\n" +
                "   Athens is home to two UNESCO World Heritage Sites, the Acropolis of Athens and the medieval Daphni Monastery. Landmarks of the modern era, dating back to the establishment of Athens as the capital of the independent Greek state in 1834, include the Hellenic Parliament (19th century) and the Athens Trilogy, consisting of the National Library of Greece, the Athens University and the Academy of Athens. Athens was the host city of the first modern-day Olympic Games in 1896, and 108 years later it welcomed home the 2004 Summer Olympics.[19] Athens is also home to several large museums, such as the National Archeological Museum, featuring the world's largest collection of ancient Greek antiquities, the Byzantine and Christian Museum and the new Acropolis Museum."),"   Greece (Greek: Ελλάδα, Elláda [eˈlaða] ( listen)), officially the Hellenic Republic (Greek: Ελληνική Δημοκρατία Ellīnikī́ Dīmokratía [eliniˈci ðimokraˈti.a]), also known since ancient times as Hellas ([ˈhɛləs]) (Ancient Greek: Ἑλλάς Hellás,[8][9][10][11][12][13][14][15] is a country located in southeastern Europe. According to the 2015 census, Greece's population is approximately 10.9 million. Athens is the nation's capital and largest city, followed by Thessaloniki.\n" +
                "   Greece is strategically located at the crossroads of Europe, Asia, and Africa. Situated on the southern tip of the Balkan peninsula, it shares land borders with Albania to the northwest, the Republic of Macedonia and Bulgaria to the north and Turkey to the northeast. Greece consists of nine geographic regions: Macedonia, Central Greece, the Peloponnese, Thessaly, Epirus, the Aegean Islands (including the Dodecanese and Cyclades), Thrace, Crete, and the Ionian Islands. The Aegean Sea lies to the east of the mainland, the Ionian Sea to the west, and the Mediterranean Sea to the south. Greece has the longest coastline on the Mediterranean Basin and the 11th longest coastline in the world at 13,676 km (8,498 mi) in length, featuring a vast number of islands, of which 227 are inhabited. Eighty percent of Greece is mountainous, with Mount Olympus being the highest peak at 2,918 metres (9,573 ft).\n" +
                "   The history of Greece is one of the longest of any country, having been continuously inhabited since 270,000 BC. Considered the cradle of Western civilization, Greece was the birthplace of democracy, Western philosophy, the Olympic Games, Western literature, historiography, political science, major scientific and mathematical principles, and Western drama, including both tragedy and comedy.[16] The Greeks were first unified under Philip of Macedon in the fourth century BC. His son Alexander the Great rapidly conquered much of the ancient world, spreading Greek culture and science from the eastern Mediterranean to the Indus River. Greece was annexed by Rome in the second century BC, becoming an integral part of the Roman Empire and its successor, the Byzantine Empire. The first century AD saw the establishment of the Greek Orthodox Church, which shaped modern Greek identity and transmitted Greek traditions to the wider Orthodox World.[17] Falling under Ottoman dominion in the mid-15th century, the modern nation state of Greece emerged in 1830 following a war of independence. Greece's rich historical legacy is reflected in large part by its 18 UNESCO World Heritage Sites, among the most in Europe and the world.[18]\n" +
                "   Greece is a democratic and developed country with an advanced high-income economy, a high quality of life and a very high standard of living. A founding member of the United Nations, Greece was the tenth member to join the European Communities (precursor to the European Union) and has been part of the Eurozone since 2001. It is also a member of numerous other international institutions, including the Council of Europe, North Atlantic Treaty Organization (NATO), Organisation for Economic Co-operation and Development (OECD), WTO, OSCE, and the OIF. Greece's unique cultural heritage, subsequently large tourism industry, and prominent shipping sector classify it as a middle power. It is the largest economy in the Balkans, where it is an important regional investor.",R.drawable.greece_emblem));
    }
}


